name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo .

      - name: Configure Docker authentication
        uses: google-github-actions/auth@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo

      - name: Deploy to Compute Engine
        run: |
          gcloud compute instances update-container instance-wif-github \
            --container-image gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo\
            --zone us-central1-a
        # env:
        #   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        #   INSTANCE_NAME: instance-wif-github
        #   INSTANCE_ZONE: us-central1-a
