name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo .

      - name: Configure Docker authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true
          cleanup_credentials: true

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo 

      - name: Deploy to Compute Engine 
        run: |
          gcloud compute instances update-container instance-wif-github \
            --container-image gcr.io/us-central1-docker.pkg.dev/midyear-byway-418606/wif-demo \
            --zone us-central1-a
